const products = [
  {
    id: 1,
    name: "Grilled Cheese",
    category: "Lunch",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: "44.50",
    rating: 5,
    discount: 50,
    oldPrice: "50,50",
    images: [
      "../assets/images/products/1.png",
      "../assets/images/products/2.png",
      "../assets/images/products/3.png",
      "../assets/images/products/4.png",
    ],
  },
  {
    id: 2,
    name: "Steak",
    category: "Dinner",
    description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    price: "44,50",
    rating: 4.5,
    discount: 50,
    oldPrice: "50,50",
    images: [
      "../assets/images/products/2.png",
      "../assets/images/products/3.png",
      "../assets/images/products/4.png",
      "../assets/images/products/5.png",
    ],
  },
  {
    id: 3,
    name: "Salmon",
    category: "Dinner",
    description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: "44,50",
    rating: 4.5,
    discount: 50,
    oldPrice: "50,50",
    images: [
      "../assets/images/products/3.png",
      "../assets/images/products/4.png",
      "../assets/images/products/5.png",
      "../assets/images/products/6.png",
    ],
  },
  {
    id: 4,
    name: "Chicken Alfredo",
    category: "Dinner",
    description: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    price: "44,50",
    rating: 4,
    discount: 50,
    oldPrice: "50,50",
    images: [
      "../assets/images/products/4.png",
      "../assets/images/products/5.png",
      "../assets/images/products/6.png",
      "../assets/images/products/1.png",
    ],
  },
  {
    id: 5,
    name: "Lasagna",
    category: "Dinner",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: "77,99",
    rating: 1,
    discount: 99,
    oldPrice: "50,50",
    images: [
      "../assets/images/products/5.png",
      "../assets/images/products/6.png",
      "../assets/images/products/1.png",
      "../assets/images/products/2.png",
    ],
  },
  {
    id: 6,
    name: "Chocolate Chip Cookies",
    category: "Dessert",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: "599,99",
    rating: 3.5,
    discount: 15,
    oldPrice: "50,50",
    images: [
      "../assets/images/products/6.png",
      "../assets/images/products/1.png",
      "../assets/images/products/2.png",
      "../assets/images/products/3.png",
    ],
  },
  {
    id: 7,
    name: "Chocolate Chip Cookies",
    category: "Dessert",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: "49,39",
    rating: 3.5,
    discount: 25,
    oldPrice: "50,50",
    images: [
      "../assets/images/products/1.png",
      "../assets/images/products/2.png",
      "../assets/images/products/3.png",
      "../assets/images/products/4.png",
    ],
  },
];
